---
title: "Biométrie humaine"
author: "___"
date: "___"
output: html_document
---

<!--# ATTENTION: à chaque fois que cela se justifie, utilisez un chaînage des opérations. Prenez soin d'écrire un code clair, lisible, et qui utilise les fonctions ad hoc de manière optimale (recherchez une solution concise et efficace). -->

```{r setup}
SciViews::R
```

## Importation des données

<!--% Importez le jeu de données `biometry` depuis le package {BioDataScience} en utilisant l'option lang = "FR". Assignez-le à la variable `biometry`. -->

```{r import}

```

<!--% Visualisez les 10 premières lignes de `biometry` pour prendre connaissance du contenu du jeu de données. -->

```{r tableau}

```

## Remaniement des données

<!--% Calculez l'IMC (BMI en anglais) et créez une variable nommée `bmi` dans `biometry`. Créez une seconde variable `bmi_f` sous forme de facteur qui reprend la catégorisation de l'IMC telle que réalisée par l'OMS. -->

```{r imc}

```

## Description des données

### IMC

<!--% Dénombrez les hommes et les femmes dans chacune des catégories de `bmi_f`. Présentez cette table correctement dans le document R Markdown (formattage et légende de la table). -->

```{r imc_tab}

```

<!--% Choisissez le graphique le plus adapté et ajoutez-lui une légende pour représenter visuellement votre jeu de données. -->

```{r imc_graph}

```

<!--% Commentez la table et le graphique que vous venez de réaliser en maximum 5 phrases. -->

### Âge

<!--% Représentez graphiquement l'âge des individus de la manière la plus judicieuse pour déterminer s'il existe plusieurs modes dans le jeu de données. Commentez votre graphique en maximum 5 phrases. -->

```{r age}

```

<!--% Calculez une nouvelle variable qualitative `age_o` qui sépare les données en fonction de sous-populations représentatives de ces différents modes. Cette variable doit être encodée sous forme de facteur ordonné avec les niveaux classés par âge croissant. -->

```{r age_group}

```

<!--% Créez une table qui résume les caractéristiques principales de ces sous-populations : nombre d'observations et IMC moyen. Commentez votre table ensuite en maximum 5 phrases. -->

```{r age_imc}

```

<!--% Extrayez un sous-tableau qui sera nommé `bio_jeune` et qui contiendra uniquement le sous-groupe le plus jeune. Ensuite, éliminez les autres niveaux de la variable `age_o` dans `bio_jeune`. Raccourcissez encore ce tableau en ne gardant que les variables `gender`, `age` et `bmi`. -->

```{r jeune}

```
