---
title: "Croissance de coraux en mésocosme"
author: "___"
date: "___"
output: html_document
---

```{r setup}
SciViews::R(lang = "fr")
```

## Introduction

Les mésocosmes sont des récifs artificiels qui permettent d'étudier entre autres les coraux dans des conditions contrôlées. La croissance de deux espèces de coraux est étudiée.

## Analyse

### Importation des données

<!--% Importez le jeu de données depuis le lien fourni dans le README et assignez-le à la variable `coral`. -->

```{r import}
# Création du dossier data/
fs::dir_create("../data/")
# Importation des données
coral <- read$csv("___", cache_file = "../data/corals.csv") 
```

<!--# Notez que l'argument `cache_file=` permet de sauver localement le jeu de données dans le dossier data/. Lors des prochaines utilisations de la fonction read(), le tableau sera chargé depuis la version locale..-->

<!--% Explorez les variables de votre jeu de données avec la fonction `skim()` du package {skimr}. -->

```{r explo}

```

### Remaniement des données

<!--% Calculez les variables suivantes en une seule étape et ajoutez-les à `coral` -->

<!--% 1) Divisez le gain par le nombre de jours d'expérience, en g/j dans `gain_j`. -->

<!--% 2) Divisez le gain standardisé par le nombre de jours et multipliez cette nouvelle variable par 100 pour obtenir la croissance en %/j dans `gain_std_j`. -->

<!--% 3) Transformez les variables `localisation` et `species` en variables facteurs. -->

```{r calcul}

```

<!--% En utilisant le chainage des opérations. Réalisez un tableau réduit en retirant les variables `time`, `temperature` et `date`. Retirez également les individus ayant des valeurs de `gain_std` strictement inférieur à -0.1. Assignez ce résultat à coral2-->

```{r selection}

```

### Description des données

<!--% Réalisez un  tableau résumant les données par aquarium et par espèce. Ce tableau doit contenir le nombre d'observations, la valeur minimale, la valeur maximale, la médiane et la moyenne..-->

```{r tab}

```

<!-- Interprétez le tableau ci-dessus en maximum 3 phrases.s-->

<!-- BONUS : Réalisez un graphique pertinent afin de décrire les données.-->

```{r plot_bonus}

```

<!-- BONUS : Interprétez le graphique ci-dessus en maximum 3 phrases.s-->
